# Generated by Django 5.1.4 on 2025-02-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_alter_freelancer_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='owner',
            new_name='user',
        ),
    ]
