image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      # Install pyenv and Python 3.10.12
      curl https://pyenv.run | bash
      export PATH="$HOME/.pyenv/bin:$PATH"
      export PYENV_ROOT="$HOME/.pyenv"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
      pyenv install 3.10.12
      pyenv global 3.10.12
      # Start PostgreSQL
      . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: |
      # Ensure Python 3.10 is being used
      python --version
      /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: |
      . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &

vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
