# Generated by Django 5.1.4 on 2025-02-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
