# Generated by Django 5.1.4 on 2025-02-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_skill_clientprofile_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ClientProfile',
        ),
        migrations.AddField(
            model_name='listing',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
