# Generated by Django 5.1.4 on 2025-02-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_listing_clientprofile_listing_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
