# Generated by Django 5.1.4 on 2025-02-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_listing'),
    ]

    operations = [
    ]
