# Generated by Django 5.1.4 on 2025-02-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250215_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='custom_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
