# Generated by Django 5.1.4 on 2025-02-15 12:50

from django.db import migrations

def add_predefined_skills(apps, schema_editor):
    Skill = apps.get_model('accounts', 'Skill')
    skills = [
        # Tech Skills
        'Python', 'JavaScript', 'React', 'Node.js', 'Django', 'SQL', 'PostgreSQL', 'AWS', 'Kubernetes', 'Docker',
        'Linux', 'Cloud Computing', 'Machine Learning', 'Data Science', 'AI', 'Cybersecurity', 'DevOps', 'Git/GitHub',
        
        # Finance Skills
        'Accounting', 'Financial Analysis', 'Budgeting', 'Risk Management', 'Taxation', 'Investment Strategies',
        'Financial Reporting', 'Financial Modelling', 'Portfolio Management', 'Banking', 'Audit', 'Financial Forecasting',
        'Corporate Finance', 'Mergers and Acquisitions', 'Blockchain', 'Cryptocurrency', 'Excel (Advanced)',

        # Healthcare Skills
        'Medical Coding', 'Patient Care', 'Clinical Research', 'Healthcare Administration', 'Nursing', 'Pharmacy',
        'Health Informatics', 'Telemedicine', 'Medical Billing', 'Epidemiology', 'Mental Health', 'Public Health',
        'Radiology', 'Surgery Assistance', 'Emergency Medical Technician', 'Health Insurance', 'Medical Transcription',

        # Marketing Skills
        'Social Media Marketing', 'SEO', 'SEM', 'Content Marketing', 'Digital Marketing', 'Brand Management', 
        'Marketing Strategy', 'Marketing Analytics', 'Email Marketing', 'Affiliate Marketing', 'Influencer Marketing',
        'PPC', 'Market Research', 'Consumer Behavior', 'Public Relations', 'Event Planning', 'Copywriting',

        # Education Skills
        'Teaching', 'Curriculum Design', 'Lesson Planning', 'Educational Technology', 'Classroom Management',
        'Special Education', 'E-learning', 'Tutoring', 'Language Teaching', 'Instructional Design', 'Academic Research',
        'Pedagogy', 'Student Assessment', 'Online Education', 'Educational Psychology', 'Mentoring', 'Adult Education'
    ]
    
    for skill in skills:
        Skill.objects.get_or_create(name=skill)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_freelancerprofile_custom_skills'),
    ]

    operations = [
    ]
