# Generated by Django 5.1.4 on 2025-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250215_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='Category',
            field=models.CharField(default='Misc', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
