# Generated by Django 5.1.4 on 2024-12-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
