# Generated by Django 5.1.4 on 2025-02-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_listing'),
        ('job_listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(help_text='A short summary of the job', max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('marketing', 'Marketing'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(blank=True, help_text='e.g. $50,000 - $70,000', max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract')], default='full-time', max_length=50)),
                ('remote', models.BooleanField(default=False)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
