# Generated by Django 5.1.4 on 2025-04-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0003_listing_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Company',
            new_name='company',
        ),
    ]
